export const  currencies = [
  { "value": "KZ", "label": "KZ - Unknown Currency" },
  { "value": "XCD", "label": "XCD - East Caribbean Dollar" },
  { "value": "ARS", "label": "ARS - Argentine Peso" },
  { "value": "AMD", "label": "AMD - Armenian Dram" },
  { "value": "BHD", "label": "BHD - Bahraini Dinar" },
  { "value": "BZD", "label": "BZD - Belize Dollar" },
  { "value": "BMD", "label": "BMD - Bermudian Dollar" },
  { "value": "BTN", "label": "BTN - Bhutanese Ngultrum" },
  { "value": "BOB", "label": "BOB - Boliviano" },
  { "value": "BAM", "label": "BAM - Bosnia and Herzegovina Convertible Mark" },
  { "value": "BWP", "label": "BWP - Botswana Pula" },
  { "value": "BND", "label": "BND - Brunei Dollar" },
  { "value": "BGN", "label": "BGN - Bulgarian Lev" },
  { "value": "BIF", "label": "BIF - Burundian Franc" },
  { "value": "KHR", "label": "KHR - Cambodian Riel" },
  { "value": "XAF", "label": "XAF - Central African CFA Franc" },
  { "value": "CAD", "label": "CAD - Canadian Dollar" },
  { "value": "CVE", "label": "CVE - Cape Verdean Escudo" },
  { "value": "KYD", "label": "KYD - Cayman Islands Dollar" },
  { "value": "CLP", "label": "CLP - Chilean Peso" },
  { "value": "KMF", "label": "KMF - Comorian Franc" },
  { "value": "CDF", "label": "CDF - Congolese Franc" },
  { "value": "CRC", "label": "CRC - Costa Rican Colón" },
  { "value": "HRK", "label": "HRK - Croatian Kuna" },
  { "value": "CYP", "label": "CYP - Cypriot Pound" },
  { "value": "DKK", "label": "DKK - Danish Krone" },
  { "value": "DJF", "label": "DJF - Djiboutian Franc" },
  { "value": "DOP", "label": "DOP - Dominican Peso" },
  { "value": "EGP", "label": "EGP - Egyptian Pound" },
  { "value": "ERN", "label": "ERN - Eritrean Nakfa" },
  { "value": "ETB", "label": "ETB - Ethiopian Birr" },
  { "value": "FKP", "label": "FKP - Falkland Islands Pound" },
  { "value": "FJD", "label": "FJD - Fijian Dollar" },
  { "value": "GMD", "label": "GMD - Gambian Dalasi" },
  { "value": "GHS", "label": "GHS - Ghanaian Cedi" },
  { "value": "GIP", "label": "GIP - Gibraltar Pound" },
  { "value": "GTQ", "label": "GTQ - Guatemalan Quetzal" },
  { "value": "GNF", "label": "GNF - Guinean Franc" },
  { "value": "GYD", "label": "GYD - Guyana Dollar" },
  { "value": "HTG", "label": "HTG - Haitian Gourde" },
  { "value": "HNL", "label": "HNL - Honduran Lempira" },
  { "value": "HKD", "label": "HKD - Hong Kong Dollar" },
  { "value": "HUF", "label": "HUF - Hungarian Forint" },
  { "value": "IDR", "label": "IDR - Indonesian Rupiah" },
  { "value": "IQD", "label": "IQD - Iraqi Dinar" },
  { "value": "ILS", "label": "ILS - Israeli New Shekel" },
  { "value": "JMD", "label": "JMD - Jamaican Dollar" },
  { "value": "JOD", "label": "JOD - Jordanian Dinar" },
  { "value": "KZT", "label": "KZT - Kazakhstani Tenge" },
  { "value": "KES", "label": "KES - Kenyan Shilling" },
  { "value": "KPW", "label": "KPW - North Korean Won" },
  { "value": "KRW", "label": "KRW - South Korean Won" },
  { "value": "KWD", "label": "KWD - Kuwaiti Dinar" },
  { "value": "KGS", "label": "KGS - Kyrgyzstani Som" },
  { "value": "LAK", "label": "LAK - Lao Kip" },
  { "value": "LVL", "label": "LVL - Latvian Lats" },
  { "value": "LSL", "label": "LSL - Lesotho Loti" },
  { "value": "LYD", "label": "LYD - Libyan Dinar" },
  { "value": "LTL", "label": "LTL - Lithuanian Litas" },
  { "value": "MOP", "label": "MOP - Macanese Pataca" },
  { "value": "MKD", "label": "MKD - Macedonian Denar" },
  { "value": "MWK", "label": "MWK - Malawian Kwacha" },
  { "value": "MYR", "label": "MYR - Malaysian Ringgit" },
  { "value": "MVR", "label": "MVR - Maldivian Rufiyaa" },
  { "value": "MRO", "label": "MRO - Mauritanian Ouguiya" },
  { "value": "MUR", "label": "MUR - Mauritian Rupee" },
  { "value": "MXN", "label": "MXN - Mexican Peso" },
  { "value": "MDL", "label": "MDL - Moldovan Leu" },
  { "value": "MNT", "label": "MNT - Mongolian Tögrög" },
  { "value": "MMK", "label": "MMK - Burmese Kyat" },
  { "value": "NPR", "label": "NPR - Nepalese Rupee" },
  { "value": "NIO", "label": "NIO - Nicaraguan Córdoba" },
  { "value": "OMR", "label": "OMR - Omani Rial" },
  { "value": "PKR", "label": "PKR - Pakistani Rupee" },
  { "value": "PGK", "label": "PGK - Papua New Guinean Kina" },
  { "value": "PYG", "label": "PYG - Paraguayan Guarani" },
  { "value": "PEN", "label": "PEN - Peruvian Sol" },
  { "value": "PHP", "label": "PHP - Philippine Peso" },
  { "value": "PLN", "label": "PLN - Polish Zloty" },
  { "value": "QAR", "label": "QAR - Qatari Riyal" },
  { "value": "RUB", "label": "RUB - Russian Ruble" },
  { "value": "RWF", "label": "RWF - Rwandan Franc" },
  { "value": "WST", "label": "WST - Samoan Tala" },
  { "value": "STD", "label": "STD - São Tomé and Príncipe Dobra" },
  { "value": "RSD", "label": "RSD - Serbian Dinar" },
  { "value": "SLL", "label": "SLL - Sierra Leonean Leone" },
  { "value": "SGD", "label": "SGD - Singapore Dollar" },
  { "value": "SBD", "label": "SBD - Solomon Islands Dollar" },
  { "value": "ZAR", "label": "ZAR - South African Rand" },
  { "value": "SZL", "label": "SZL - Swazi Lilangeni" },
  { "value": "SEK", "label": "SEK - Swedish Krona" },
  { "value": "SYP", "label": "SYP - Syrian Pound" },
  { "value": "TWD", "label": "TWD - New Taiwan Dollar" },
  { "value": "TZS", "label": "TZS - Tanzanian Shilling" },
  { "value": "THB", "label": "THB - Thai Baht" },
  { "value": "TOP", "label": "TOP - Tongan Paʻanga" },
  { "value": "TTD", "label": "TTD - Trinidad and Tobago Dollar" },
  { "value": "TRY", "label": "TRY - Turkish Lira" },
  { "value": "TMM", "label": "TMM - Turkmenistani Manat" },
  { "value": "UGX", "label": "UGX - Ugandan Shilling" },
  { "value": "UAH", "label": "UAH - Ukrainian Hryvnia" },
  { "value": "UYU", "label": "UYU - Uruguayan Peso" },
  { "value": "UZS", "label": "UZS - Uzbekistani Som" },
  { "value": "VUV", "label": "VUV - Vanuatu Vatu" },
  { "value": "VEF", "label": "VEF - Venezuelan Bolívar" },
  { "value": "VND", "label": "VND - Vietnamese Dong" },
  { "value": "YER", "label": "YER - Yemeni Rial" },
  { "value": "ZMW", "label": "ZMW - Zambian Kwacha" },
  { "value": "ZWL", "label": "ZWL - Zimbabwean Dollar" },
  { "value": "AFN", "label": "AFN - Afghan Afghani" },
  { "value": "USD", "label": "USD - United States Dollar" },
  { "value": "AWG", "label": "AWG - Aruban Florin" },
  { "value": "CHF", "label": "CHF - Swiss Franc" },
  { "value": "DZD", "label": "DZD - Algerian Dinar" },
  { "value": "EUR", "label": "EUR - Euro" },
  { "value": "ALL", "label": "ALL - Albanian Lek" },
  { "value": "BSD", "label": "BSD - Bahamian Dollar" },
  { "value": "JPY", "label": "JPY - Japanese Yen" },
  { "value": "GBP", "label": "GBP - British Pound Sterling" },
  { "value": "XOF", "label": "XOF - West African CFA Franc" },
  { "value": "MZN", "label": "MZN - Mozambican Metical" },
  { "value": "CNY", "label": "CNY - Chinese Yuan" },
  { "value": "LBP", "label": "LBP - Lebanese Pound" },
  { "value": "NOK", "label": "NOK - Norwegian Krone" },
  { "value": "SRD", "label": "SRD - Surinamese Dollar" },
  { "value": "COP", "label": "COP - Colombian Peso" },
  { "value": "NZD", "label": "NZD - New Zealand Dollar" },
  { "value": "BDT", "label": "BDT - Bangladeshi Taka" },
  { "value": "SOS", "label": "SOS - Somali Shilling" },
  { "value": "RON", "label": "RON - Romanian Leu" },
  { "value": "LRD", "label": "LRD - Liberian Dollar" },
  { "value": "SCR", "label": "SCR - Seychellois Rupee" },
  { "value": "INR", "label": "INR - Indian Rupee" },
  { "value": "BBD", "label": "BBD - Barbadian Dollar" },
  { "value": "MAD", "label": "MAD - Moroccan Dirham" },
  { "value": "NGN", "label": "NGN - Nigerian Naira" },
  { "value": "IRR", "label": "IRR - Iranian Rial" },
  { "value": "SDG", "label": "SDG - Sudanese Pound" },
  { "value": "ISK", "label": "ISK - Icelandic Króna" },
  { "value": "BRL", "label": "BRL - Brazilian Real" },
  { "value": "SHP", "label": "SHP - Saint Helena Pound" },
  { "value": "SAR", "label": "SAR - Saudi Riyal" },
  { "value": "NAD", "label": "NAD - Namibian Dollar" },
  { "value": "CZK", "label": "CZK - Czech Koruna" },
  { "value": "LKR", "label": "LKR - Sri Lankan Rupee" },
  { "value": "CUP", "label": "CUP - Cuban Peso" },
  { "value": "AUD", "label": "AUD - Australian Dollar" },
  { "value": "AED", "label": "AED - United Arab Emirates Dirham" },
  { "value": "TND", "label": "TND - Tunisian Dinar" }
]

// export const countries = [
//   { value: "US", label: "United States" },
//   { value: "CA", label: "Canada" },
//   { value: "GB", label: "United Kingdom" },
//   { value: "DE", label: "Germany" },
//   { value: "FR", label: "France" },
//   { value: "AU", label: "Australia" },
//   { value: "JP", label: "Japan" },
//   { value: "IN", label: "India" },
//   { value: "BR", label: "Brazil" },
//   { value: "MX", label: "Mexico" },

//   // additional 50
//   { value: "AF", label: "Afghanistan" },
//   { value: "AL", label: "Albania" },
//   { value: "DZ", label: "Algeria" },
//   { value: "AO", label: "Angola" },
//   { value: "AR", label: "Argentina" },
//   { value: "AM", label: "Armenia" },
//   { value: "AZ", label: "Azerbaijan" },
//   { value: "BH", label: "Bahrain" },
//   { value: "BD", label: "Bangladesh" },
//   { value: "BB", label: "Barbados" },
//   { value: "BY", label: "Belarus" },
//   { value: "BE", label: "Belgium" },
//   { value: "BZ", label: "Belize" },
//   { value: "BJ", label: "Benin" },
//   { value: "BT", label: "Bhutan" },
//   { value: "BO", label: "Bolivia" },
//   { value: "BA", label: "Bosnia & Herzegovina" },
//   { value: "BW", label: "Botswana" },
//   { value: "BG", label: "Bulgaria" },
//   { value: "BF", label: "Burkina Faso" },
//   { value: "BI", label: "Burundi" },
//   { value: "KH", label: "Cambodia" },
//   { value: "CM", label: "Cameroon" },
//   { value: "CV", label: "Cape Verde" },
//   { value: "CF", label: "Central African Republic" },
//   { value: "TD", label: "Chad" },
//   { value: "CL", label: "Chile" },
//   { value: "CN", label: "China" },
//   { value: "CO", label: "Colombia" },
//   { value: "CR", label: "Costa Rica" },
//   { value: "CI", label: "Côte d’Ivoire" },
//   { value: "HR", label: "Croatia" },
//   { value: "CU", label: "Cuba" },
//   { value: "CY", label: "Cyprus" },
//   { value: "CZ", label: "Czech Republic" },
//   { value: "DK", label: "Denmark" },
//   { value: "DO", label: "Dominican Republic" },
//   { value: "EC", label: "Ecuador" },
//   { value: "EG", label: "Egypt" },
//   { value: "SV", label: "El Salvador" },
//   { value: "GQ", label: "Equatorial Guinea" },
//   { value: "ER", label: "Eritrea" },
//   { value: "EE", label: "Estonia" },
//   { value: "ET", label: "Ethiopia" },
//   { value: "FJ", label: "Fiji" },
//   { value: "FI", label: "Finland" },
//   { value: "GA", label: "Gabon" },
//   { value: "GM", label: "Gambia" },
//   { value: "GE", label: "Georgia" }
// ];


export const countries = [
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "AlandIslands", label: "Åland Islands" },
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "AmericanSamoa", label: "American Samoa" },
  { value: "Andorra", label: "Andorra" },
  { value: "Angola", label: "Angola" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Antarctica", label: "Antarctica" },
  { value: "AntiguaAndBarbuda", label: "Antigua and Barbuda" },
  { value: "Argentina", label: "Argentina" },
  { value: "Armenia", label: "Armenia" },
  { value: "Aruba", label: "Aruba" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Benin", label: "Benin" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivia", label: "Bolivia, Plurinational State of" },
  { value: "Bonaire", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "BosniaAndHerzegovina", label: "Bosnia and Herzegovina" },
  { value: "Botswana", label: "Botswana" },
  { value: "BouvetIsland", label: "Bouvet Island" },
  { value: "Brazil", label: "Brazil" },
  { value: "BritishIndianOceanTerritory", label: "British Indian Ocean Territory" },
  { value: "BruneiDarussalam", label: "Brunei Darussalam" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "BurkinaFaso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Canada", label: "Canada" },
  { value: "CapeVerde", label: "Cape Verde" },
  { value: "CaymanIslands", label: "Cayman Islands" },
  { value: "CentralAfricanRepublic", label: "Central African Republic" },
  { value: "Chad", label: "Chad" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "ChristmasIsland", label: "Christmas Island" },
  { value: "CocosIslands", label: "Cocos (Keeling) Islands" },
  { value: "Colombia", label: "Colombia" },
  { value: "Comoros", label: "Comoros" },
  { value: "Congo", label: "Congo" },
  { value: "CongoDemocraticRepublic", label: "Congo, The Democratic Republic of the" },
  { value: "CookIslands", label: "Cook Islands" },
  { value: "CostaRica", label: "Costa Rica" },
  { value: "Croatia", label: "Croatia" },
  { value: "Cuba", label: "Cuba" },
  { value: "Curacao", label: "Curaçao" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "CzechRepublic", label: "Czech Republic" },
  { value: "Denmark", label: "Denmark" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Dominica", label: "Dominica" },
  { value: "DominicanRepublic", label: "Dominican Republic" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "ElSalvador", label: "El Salvador" },
  { value: "EquatorialGuinea", label: "Equatorial Guinea" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Estonia", label: "Estonia" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "FalklandIslands", label: "Falkland Islands (Malvinas)" },
  { value: "FaroeIslands", label: "Faroe Islands" },
  { value: "Fiji", label: "Fiji" },
  { value: "Finland", label: "Finland" },
  { value: "France", label: "France" },
  { value: "FrenchGuiana", label: "French Guiana" },
  { value: "FrenchPolynesia", label: "French Polynesia" },
  { value: "FrenchSouthernTerritories", label: "French Southern Territories" },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambia", label: "Gambia" },
  { value: "Georgia", label: "Georgia" },
  { value: "Germany", label: "Germany" },
  { value: "Ghana", label: "Ghana" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Greece", label: "Greece" },
  { value: "Greenland", label: "Greenland" },
  { value: "Grenada", label: "Grenada" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Guam", label: "Guam" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guernsey", label: "Guernsey" },
  { value: "Guinea", label: "Guinea" },
  { value: "GuineaBissau", label: "Guinea-Bissau" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haiti", label: "Haiti" },
  { value: "HeardIsland", label: "Heard Island and McDonald Islands" },
  { value: "VaticanCity", label: "Holy See (Vatican City State)" },
  { value: "Honduras", label: "Honduras" },
  { value: "HongKong", label: "Hong Kong" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Iran", label: "Iran" },
  { value: "Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "IsleOfMan", label: "Isle of Man" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy" },
  { value: "IvoryCoast", label: "Ivory Coast" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Jersey", label: "Jersey" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "NorthKorea", label: "Korea, Democratic Peoples Republic of" },
  { value: "SouthKorea", label: "Korea, Republic of" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Laos", label: "Lao Peoples Democratic Republic" },
  { value: "Latvia", label: "Latvia" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Macao", label: "Macao" },
  { value: "Macedonia", label: "Macedonia" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Mali", label: "Mali" },
  { value: "Malta", label: "Malta" },
  { value: "MarshallIslands", label: "Marshall Islands" },
  { value: "Martinique", label: "Martinique" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Mayotte", label: "Mayotte" },
  { value: "Mexico", label: "Mexico" },
  { value: "Micronesia", label: "Micronesia, Federated States of" },
  { value: "Moldova", label: "Moldova, Republic of" },
  { value: "Monaco", label: "Monaco" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Morocco", label: "Morocco" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Namibia", label: "Namibia" },
  { value: "Nauru", label: "Nauru" },
  { value: "Nepal", label: "Nepal" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "NewCaledonia", label: "New Caledonia" },
  { value: "NewZealand", label: "New Zealand" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Niue", label: "Niue" },
  { value: "NorfolkIsland", label: "Norfolk Island" },
  { value: "NorthernMarianaIslands", label: "Northern Mariana Islands" },
  { value: "Norway", label: "Norway" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Palau", label: "Palau" },
  { value: "Palestine", label: "Palestinian Territory, Occupied" },
  { value: "Panama", label: "Panama" },
  { value: "PapuaNewGuinea", label: "Papua New Guinea" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Peru" },
  { value: "Philippines", label: "Philippines" },
  { value: "Pitcairn", label: "Pitcairn" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "PuertoRico", label: "Puerto Rico" },
  { value: "Qatar", label: "Qatar" },
  { value: "Reunion", label: "Réunion" },
  { value: "Romania", label: "Romania" },
  { value: "Russia", label: "Russian Federation" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "SaintBarthelemy", label: "Saint Barthélemy" },
  { value: "SaintHelena", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "SaintKittsAndNevis", label: "Saint Kitts and Nevis" },
  { value: "SaintLucia", label: "Saint Lucia" },
  { value: "SaintMartin", label: "Saint Martin (French part)" },
  { value: "SaintPierreAndMiquelon", label: "Saint Pierre and Miquelon" },
  { value: "SaintVincentAndGrenadines", label: "Saint Vincent and the Grenadines" },
  { value: "Samoa", label: "Samoa" },
  { value: "SanMarino", label: "San Marino" },
  { value: "SaoTomeAndPrincipe", label: "Sao Tome and Principe" },
  { value: "SaudiArabia", label: "Saudi Arabia" },
  { value: "Senegal", label: "Senegal" },
  { value: "Serbia", label: "Serbia" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "SierraLeone", label: "Sierra Leone" },
  { value: "Singapore", label: "Singapore" },
  { value: "SintMaarten", label: "Sint Maarten (Dutch part)" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "SolomonIslands", label: "Solomon Islands" },
  { value: "Somalia", label: "Somalia" },
  { value: "SouthAfrica", label: "South Africa" },
  { value: "SouthGeorgia", label: "South Georgia and the South Sandwich Islands" },
  { value: "SouthSudan", label: "South Sudan" },
  { value: "Spain", label: "Spain" },
  { value: "SriLanka", label: "Sri Lanka" },
  { value: "Sudan", label: "Sudan" },
  { value: "Suriname", label: "Suriname" },
  { value: "Svalbard", label: "Svalbard and Jan Mayen" },
  { value: "Swaziland", label: "Swaziland" },
  { value: "Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Syria", label: "Syria" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Thailand", label: "Thailand" },
  { value: "TimorLeste", label: "Timor-Leste" },
  { value: "Togo", label: "Togo" },
  { value: "Tokelau", label: "Tokelau" },
  { value: "Tonga", label: "Tonga" },
  { value: "TrinidadAndTobago", label: "Trinidad and Tobago" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Turkey", label: "Turkey" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "TurksAndCaicosIslands", label: "Turks and Caicos Islands" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Uganda", label: "Uganda" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "UAE", label: "United Arab Emirates" },
  { value: "UK", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "USMinorIslands", label: "United States Minor Outlying Islands" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Venezuela", label: "Venezuela, Bolivarian Republic of" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "BritishVirginIslands", label: "Virgin Islands, British" },
  { value: "USVirginIslands", label: "Virgin Islands, U.S." },
  { value: "WallisAndFutuna", label: "Wallis and Futuna" },
  { value: "WesternSahara", label: "Western Sahara" },
  { value: "Yemen", label: "Yemen" },
  { value: "Zambia", label: "Zambia" },
  { value: "Zimbabwe", label: "Zimbabwe" }
];

export const accountsModules = [
  {name: 'Accounts', label: 'Accounts'},
  {name: "Assets", label: "Assets"},
  {name: "Automation", label: "Automation"},
  {name: "Bulk_Transaction", label: "Bulk Transaction"},
  {name: "Buying", label: "Buying"},
  {name: "Communication", label: "Communication"},
  {name: "Contacts", label: "Contacts"},
  {name: "CRM", label: "CRM"},
  {name: "Custom", label: "Custom"},
  {name: "Email", label: "Email"},
  {name: "ERPNext_Integrations", label: "ERPNext Integrations"},
  {name: "Geo", label: "Geo"},
  {name: "HR", label: "HR"},
  {name: "Integrations", label: "Integrations"},
  {name: "Maintenance", label: "Maintenance"},
  {name: "Manufacturing", label: "Manufacturing"},
  {name: "Payroll", label: "Payroll"},
  {name: "Portal", label: "Portal"},
  {name: "Printing", label: "Printing"},
  {name: "Projects", label: "Projects"},
  {name: "Quality_Management", label: "Quality Management"},
  {name: "Selling", label:"Selling"},
  {name: "Social", label:"Social"},
  {name: "Stock", label:"Stock"},
  {name: "Subcontracting", label:"Subcontracting"},
  {name: "Support", label:"Support"},
];

export const accessRoles = [
  {
    id: "Accounts",
    roles: [
      "Accounts Manager",
      "Accounts User",
      "Auditor",
      "Expense Approver",
      "Report Manager",
      "System Manager"
    ]
  },
  {
    id: "Assets",
    roles: [
      "Accounts Manager",
      "Accounts User",
      "System Manager"
    ]
  },
  {
    id: "Bulk Transaction",
    roles: [
      "Accounts Manager",
      "Sales Manager",
      "Purchase Manager",
      "Stock Manager"
    ]
  },
  {
    id: "Buying",
    roles: [
      "Purchase Manager",
      "Purchase Master Manager",
      "Purchase User",
      "Supplier",
      "Accounts User"
    ]
  },
  {
    id: "Communication",
    roles: [
      "Inbox User",
      "Support Team",
      "Customer",
      "System Manager",
      "Sales User",
      "Sales Manager"
    ]
  },
  {
    id: "Email",
    roles: [
      "Inbox User",
      "Support Team",
      "Customer",
      "System Manager",
      "Sales User"
    ]
  },
  {
    id: "Contacts",
    roles: [
      "Sales User",
      "Sales Manager",
      "Customer",
      "Supplier",
      "Support Team",
      "System Manager"
    ]
  },
  {
    id: "CRM",
    roles: [
      "Sales User",
      "Sales Manager",
      "Sales Master Manager",
      "Customer",
      "Support Team",
      "Dashboard Manager"
    ]
  },
  {
    id: "Custom",
    roles: [
      "System Manager",
      "Script Manager",
      "Workspace Manager",
      "Report Manager"
    ]
  },
  {
    id: "Automation",
    roles: [
      "System Manager",
      "Script Manager",
      "Workspace Manager",
      "Report Manager"
    ]
  },
  {
    id: "Desk Module",
    roles: [
      "All roles (generic UI access)",
      "System Manager"
    ]
  },
  {
    id: "ERPNext Integrations",
    roles: [
      "System Manager",
      "Accounts Manager"
    ]
  },
  {
    id: "Geo",
    roles: [
      "System Manager",
      "HR Manager",
      "Sales Manager",
      "Projects Manager"
    ]
  },
  {
    id: "HR",
    roles: [
      "HR Manager",
      "HR User",
      "Employee",
      "Employee Self Service",
      "Leave Approver",
      "Interviewer",
      "Expense Approver"
    ]
  },
  {
    id: "Maintenance",
    roles: [
      "Maintenance Manager",
      "Maintenance User",
      "Support Team"
    ]
  },
  {
    id: "Manufacturing",
    roles: [
      "Manufacturing Manager",
      "Manufacturing User",
      "Stock Manager",
      "Quality Manager"
    ]
  },
  {
    id: "Payroll",
    roles: [
      "HR Manager",
      "Accounts Manager",
      "Expense Approver"
    ]
  },
  {
    id: "Portal",
    roles: [
      "Customer",
      "Supplier",
      "Website Manager",
      "Blogger",
      "Knowledge Base Contributor",
      "Knowledge Base Editor"
    ]
  },
  {
    id: "Printing",
    roles: [
      "System Manager",
      "Report Manager",
      "Workspace Manager"
    ]
  },
  {
    id: "Projects",
    roles: [
      "Projects Manager",
      "Projects User",
      "Employee",
      "Customer"
    ]
  },
  {
    id: "Quality Management",
    roles: [
      "Quality Manager",
      "Manufacturing Manager",
      "Stock Manager"
    ]
  },
  {
    id: "Selling",
    roles: [
      "Sales User",
      "Sales Manager",
      "Sales Master Manager",
      "Customer"
    ]
  },
  {
    id: "Social",
    roles: [
      "Blogger",
      "Newsletter Manager",
      "Website Manager"
    ]
  },
  {
    id: "Stock",
    roles: [
      "Stock Manager",
      "Stock User",
      "Manufacturing Manager",
      "Purchase User"
    ]
  },
  {
    id: "Subcontracting",
    roles: [
      "Purchase Manager",
      "Manufacturing Manager",
      "Stock Manager"
    ]
  },
  {
    id: "Support",
    roles: [
      "Support Team",
      "Customer",
      "Employee Self Service"
    ]
  }
];
