export const  currencies = [
  { "value": "KZ", "label": "KZ - Unknown Currency" },
  { "value": "XCD", "label": "XCD - East Caribbean Dollar" },
  { "value": "ARS", "label": "ARS - Argentine Peso" },
  { "value": "AMD", "label": "AMD - Armenian Dram" },
  { "value": "BHD", "label": "BHD - Bahraini Dinar" },
  { "value": "BZD", "label": "BZD - Belize Dollar" },
  { "value": "BMD", "label": "BMD - Bermudian Dollar" },
  { "value": "BTN", "label": "BTN - Bhutanese Ngultrum" },
  { "value": "BOB", "label": "BOB - Boliviano" },
  { "value": "BAM", "label": "BAM - Bosnia and Herzegovina Convertible Mark" },
  { "value": "BWP", "label": "BWP - Botswana Pula" },
  { "value": "BND", "label": "BND - Brunei Dollar" },
  { "value": "BGN", "label": "BGN - Bulgarian Lev" },
  { "value": "BIF", "label": "BIF - Burundian Franc" },
  { "value": "KHR", "label": "KHR - Cambodian Riel" },
  { "value": "XAF", "label": "XAF - Central African CFA Franc" },
  { "value": "CAD", "label": "CAD - Canadian Dollar" },
  { "value": "CVE", "label": "CVE - Cape Verdean Escudo" },
  { "value": "KYD", "label": "KYD - Cayman Islands Dollar" },
  { "value": "CLP", "label": "CLP - Chilean Peso" },
  { "value": "KMF", "label": "KMF - Comorian Franc" },
  { "value": "CDF", "label": "CDF - Congolese Franc" },
  { "value": "CRC", "label": "CRC - Costa Rican Colón" },
  { "value": "HRK", "label": "HRK - Croatian Kuna" },
  { "value": "CYP", "label": "CYP - Cypriot Pound" },
  { "value": "DKK", "label": "DKK - Danish Krone" },
  { "value": "DJF", "label": "DJF - Djiboutian Franc" },
  { "value": "DOP", "label": "DOP - Dominican Peso" },
  { "value": "EGP", "label": "EGP - Egyptian Pound" },
  { "value": "ERN", "label": "ERN - Eritrean Nakfa" },
  { "value": "ETB", "label": "ETB - Ethiopian Birr" },
  { "value": "FKP", "label": "FKP - Falkland Islands Pound" },
  { "value": "FJD", "label": "FJD - Fijian Dollar" },
  { "value": "GMD", "label": "GMD - Gambian Dalasi" },
  { "value": "GHS", "label": "GHS - Ghanaian Cedi" },
  { "value": "GIP", "label": "GIP - Gibraltar Pound" },
  { "value": "GTQ", "label": "GTQ - Guatemalan Quetzal" },
  { "value": "GNF", "label": "GNF - Guinean Franc" },
  { "value": "GYD", "label": "GYD - Guyana Dollar" },
  { "value": "HTG", "label": "HTG - Haitian Gourde" },
  { "value": "HNL", "label": "HNL - Honduran Lempira" },
  { "value": "HKD", "label": "HKD - Hong Kong Dollar" },
  { "value": "HUF", "label": "HUF - Hungarian Forint" },
  { "value": "IDR", "label": "IDR - Indonesian Rupiah" },
  { "value": "IQD", "label": "IQD - Iraqi Dinar" },
  { "value": "ILS", "label": "ILS - Israeli New Shekel" },
  { "value": "JMD", "label": "JMD - Jamaican Dollar" },
  { "value": "JOD", "label": "JOD - Jordanian Dinar" },
  { "value": "KZT", "label": "KZT - Kazakhstani Tenge" },
  { "value": "KES", "label": "KES - Kenyan Shilling" },
  { "value": "KPW", "label": "KPW - North Korean Won" },
  { "value": "KRW", "label": "KRW - South Korean Won" },
  { "value": "KWD", "label": "KWD - Kuwaiti Dinar" },
  { "value": "KGS", "label": "KGS - Kyrgyzstani Som" },
  { "value": "LAK", "label": "LAK - Lao Kip" },
  { "value": "LVL", "label": "LVL - Latvian Lats" },
  { "value": "LSL", "label": "LSL - Lesotho Loti" },
  { "value": "LYD", "label": "LYD - Libyan Dinar" },
  { "value": "LTL", "label": "LTL - Lithuanian Litas" },
  { "value": "MOP", "label": "MOP - Macanese Pataca" },
  { "value": "MKD", "label": "MKD - Macedonian Denar" },
  { "value": "MWK", "label": "MWK - Malawian Kwacha" },
  { "value": "MYR", "label": "MYR - Malaysian Ringgit" },
  { "value": "MVR", "label": "MVR - Maldivian Rufiyaa" },
  { "value": "MRO", "label": "MRO - Mauritanian Ouguiya" },
  { "value": "MUR", "label": "MUR - Mauritian Rupee" },
  { "value": "MXN", "label": "MXN - Mexican Peso" },
  { "value": "MDL", "label": "MDL - Moldovan Leu" },
  { "value": "MNT", "label": "MNT - Mongolian Tögrög" },
  { "value": "MMK", "label": "MMK - Burmese Kyat" },
  { "value": "NPR", "label": "NPR - Nepalese Rupee" },
  { "value": "NIO", "label": "NIO - Nicaraguan Córdoba" },
  { "value": "OMR", "label": "OMR - Omani Rial" },
  { "value": "PKR", "label": "PKR - Pakistani Rupee" },
  { "value": "PGK", "label": "PGK - Papua New Guinean Kina" },
  { "value": "PYG", "label": "PYG - Paraguayan Guarani" },
  { "value": "PEN", "label": "PEN - Peruvian Sol" },
  { "value": "PHP", "label": "PHP - Philippine Peso" },
  { "value": "PLN", "label": "PLN - Polish Zloty" },
  { "value": "QAR", "label": "QAR - Qatari Riyal" },
  { "value": "RUB", "label": "RUB - Russian Ruble" },
  { "value": "RWF", "label": "RWF - Rwandan Franc" },
  { "value": "WST", "label": "WST - Samoan Tala" },
  { "value": "STD", "label": "STD - São Tomé and Príncipe Dobra" },
  { "value": "RSD", "label": "RSD - Serbian Dinar" },
  { "value": "SLL", "label": "SLL - Sierra Leonean Leone" },
  { "value": "SGD", "label": "SGD - Singapore Dollar" },
  { "value": "SBD", "label": "SBD - Solomon Islands Dollar" },
  { "value": "ZAR", "label": "ZAR - South African Rand" },
  { "value": "SZL", "label": "SZL - Swazi Lilangeni" },
  { "value": "SEK", "label": "SEK - Swedish Krona" },
  { "value": "SYP", "label": "SYP - Syrian Pound" },
  { "value": "TWD", "label": "TWD - New Taiwan Dollar" },
  { "value": "TZS", "label": "TZS - Tanzanian Shilling" },
  { "value": "THB", "label": "THB - Thai Baht" },
  { "value": "TOP", "label": "TOP - Tongan Paʻanga" },
  { "value": "TTD", "label": "TTD - Trinidad and Tobago Dollar" },
  { "value": "TRY", "label": "TRY - Turkish Lira" },
  { "value": "TMM", "label": "TMM - Turkmenistani Manat" },
  { "value": "UGX", "label": "UGX - Ugandan Shilling" },
  { "value": "UAH", "label": "UAH - Ukrainian Hryvnia" },
  { "value": "UYU", "label": "UYU - Uruguayan Peso" },
  { "value": "UZS", "label": "UZS - Uzbekistani Som" },
  { "value": "VUV", "label": "VUV - Vanuatu Vatu" },
  { "value": "VEF", "label": "VEF - Venezuelan Bolívar" },
  { "value": "VND", "label": "VND - Vietnamese Dong" },
  { "value": "YER", "label": "YER - Yemeni Rial" },
  { "value": "ZMW", "label": "ZMW - Zambian Kwacha" },
  { "value": "ZWL", "label": "ZWL - Zimbabwean Dollar" },
  { "value": "AFN", "label": "AFN - Afghan Afghani" },
  { "value": "USD", "label": "USD - United States Dollar" },
  { "value": "AWG", "label": "AWG - Aruban Florin" },
  { "value": "CHF", "label": "CHF - Swiss Franc" },
  { "value": "DZD", "label": "DZD - Algerian Dinar" },
  { "value": "EUR", "label": "EUR - Euro" },
  { "value": "ALL", "label": "ALL - Albanian Lek" },
  { "value": "BSD", "label": "BSD - Bahamian Dollar" },
  { "value": "JPY", "label": "JPY - Japanese Yen" },
  { "value": "GBP", "label": "GBP - British Pound Sterling" },
  { "value": "XOF", "label": "XOF - West African CFA Franc" },
  { "value": "MZN", "label": "MZN - Mozambican Metical" },
  { "value": "CNY", "label": "CNY - Chinese Yuan" },
  { "value": "LBP", "label": "LBP - Lebanese Pound" },
  { "value": "NOK", "label": "NOK - Norwegian Krone" },
  { "value": "SRD", "label": "SRD - Surinamese Dollar" },
  { "value": "COP", "label": "COP - Colombian Peso" },
  { "value": "NZD", "label": "NZD - New Zealand Dollar" },
  { "value": "BDT", "label": "BDT - Bangladeshi Taka" },
  { "value": "SOS", "label": "SOS - Somali Shilling" },
  { "value": "RON", "label": "RON - Romanian Leu" },
  { "value": "LRD", "label": "LRD - Liberian Dollar" },
  { "value": "SCR", "label": "SCR - Seychellois Rupee" },
  { "value": "INR", "label": "INR - Indian Rupee" },
  { "value": "BBD", "label": "BBD - Barbadian Dollar" },
  { "value": "MAD", "label": "MAD - Moroccan Dirham" },
  { "value": "NGN", "label": "NGN - Nigerian Naira" },
  { "value": "IRR", "label": "IRR - Iranian Rial" },
  { "value": "SDG", "label": "SDG - Sudanese Pound" },
  { "value": "ISK", "label": "ISK - Icelandic Króna" },
  { "value": "BRL", "label": "BRL - Brazilian Real" },
  { "value": "SHP", "label": "SHP - Saint Helena Pound" },
  { "value": "SAR", "label": "SAR - Saudi Riyal" },
  { "value": "NAD", "label": "NAD - Namibian Dollar" },
  { "value": "CZK", "label": "CZK - Czech Koruna" },
  { "value": "LKR", "label": "LKR - Sri Lankan Rupee" },
  { "value": "CUP", "label": "CUP - Cuban Peso" },
  { "value": "AUD", "label": "AUD - Australian Dollar" },
  { "value": "AED", "label": "AED - United Arab Emirates Dirham" },
  { "value": "TND", "label": "TND - Tunisian Dinar" }
]

export const countries = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "AU", label: "Australia" },
  { value: "JP", label: "Japan" },
  { value: "IN", label: "India" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },

  // additional 50
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AO", label: "Angola" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia & Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CV", label: "Cape Verde" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d’Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" }
];
